export default {
  'agegroup': '3',
  'cTime': '2017-05-05 09:10:56',
  'copyFrom': '',
  'isDel': 0,
  'isShow': 0,
  'paperBasicJson': '',
  'paperBasicXml': '',
  'paperCategory': '',
  'paperClass': '',
  'paperFilePath': '',
  'paperId': '2392',
  'paperRemark': '',
  'paperScore': '25.00',
  'paperStatus': 1,
  'paperStatusName': '',
  'paperTitle': '人教九年级同步听力口语自动化考试Unit 5',
  'paperType': 1,
  'paperTypeName': '',
  'precision': '0.50',
  'qstype': 0,
  'questions': [
    {
      'paperId': '5725',
      'qsContent': '你将听到一段录音，录音播放两遍。听完录音后，你将有2分钟的时间根据所听内容，键入正确答案，补全信息记录表；之后你将有1分钟的准备时间，根据信息记录表，在2分钟内进行转述，需包含所有要点。现在你有15秒钟的时间阅读题目内容。',
      'qsId': '21123',
      'qsSort': 1,
      'qsTitle': '第一部分 信息转述。（计5分）',
      'qsType': 19,
      'sourceContent': '',
      'sourceId': '',
      'sourceType': '',
      'infos': [
        {
          'answerType': 1,
          'difficulty': '',
          'infoContent': '',
          'infoContentImg': '/media/5725/Data/1555407320912298.png',
          'infoContentImgId': '33172',
          'infoContentSourceContent': '/media/5725/Data/1555407290202584.mp3',
          'infoContentSourceId': '33171',
          'infoContentSourceType': 1,
          'infoId': '53271',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 2,
          'infoSort': 1,
          'qsId': '21123',
          'skipSecond': '',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': '',
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:35:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53271',
              'itemAnswerSecond': 5,
              'itemContent': 'thrillers',
              'itemId': '75973',
              'itemKeyword': '',
              'itemPaperSort': '1_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:36:50',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'thrillers',
                  'answerId': '118970',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75973',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:36:25',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53271',
              'itemAnswerSecond': 5,
              'itemContent': 'children\'s\n\n',
              'itemId': '75974',
              'itemKeyword': '',
              'itemPaperSort': '1_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:04',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'children\'s',
                  'answerId': '118969',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75974',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:37:15',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53271',
              'itemAnswerSecond': 5,
              'itemContent': 'Picture\n',
              'itemId': '75975',
              'itemKeyword': '',
              'itemPaperSort': '1_1_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:15',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'Picture',
                  'answerId': '118971',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75975',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:37:23',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53271',
              'itemAnswerSecond': 5,
              'itemContent': 'history',
              'itemId': '75976',
              'itemKeyword': '',
              'itemPaperSort': '1_1_4',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:23',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'history',
                  'answerId': '118972',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75976',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:37:29',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53271',
              'itemAnswerSecond': 5,
              'itemContent': 'magazines',
              'itemId': '75977',
              'itemKeyword': '',
              'itemPaperSort': '1_1_5',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:29',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'magazines',
                  'answerId': '118973',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75977',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            }
          ]
        },
        {
          'answerType': 2,
          'difficulty': '',
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/media/5725/Data/1555407290202584.mp3',
          'infoContentSourceId': '33171',
          'infoContentSourceType': 1,
          'infoId': '53272',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 2,
          'qsId': '21123',
          'skipSecond': '',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': '',
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2019-04-16 17:34:30',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '53272',
              'itemAnswerSecond': 5,
              'itemContent': 'Many people like reading. Different people like reading different kinds of books. Here are the results of the discussion "What kind of books do you like reading most?" Bob said he liked to read a bit in bed every night. Thrillers are his favorite, and he made sure he read at least ten pages every night before he went to sleep. Kate is a teacher, and she loves reading books on children\'s behavior. Picture storybooks are Jack\'s favourite, because he doesn\'t have enough time to read many books now. Lucy told us if she has time, she mostly reads history books. Anne likes to read different types of books and magazines.',
              'itemId': '75972',
              'itemKeyword': '',
              'itemPaperSort': '1_2_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:39:08',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'Many people like reading. Different people like reading different kinds of books. Here are the results of the discussion "What kind of books do you like reading most?" Bob said he liked to read a bit in bed every night. Thrillers are his favorite, and he made sure he read at least ten pages every night before he went to sleep. Kate is a teacher, and she loves reading books on children\'s behavior. Picture storybooks are Jack\'s favourite, because he doesn\'t have enough time to read many books now. Lucy told us if she has time, she mostly reads history books. Anne likes to read different types of books and magazines.',
                  'answerId': '118968',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'itemId': '75972',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            }
          ]
        }
      ]
    },
    {
      'isDel': 0,
      'paperId': '1119210815337451522',
      'qsTitle': '第二部分 听较长对话回答问题（计5分）',
      'qsContent': '本部分共有5道小题，你将听到两段较长对话，每段对话听两遍。在听每段对话前，你将有时间阅读相关小题，每小题5秒钟；听完后，每小题你还有5秒钟的时间在屏幕上点击你认为最合适的备选答案。',
      'qsId': '1119210817879199746',
      'qsSort': 1,
      'qsType': 3,
      'sourceContent': '/upload/file/20170505/590c41a0c95be.mp3',
      'sourceId': '3629',
      'sourceType': 1,
      'infos': [
        {
          'qsId': '1119210817879199746',
          'infoId': '1119210818009223170',
          'infoRepetTimes': 1,
          'infoPrepareSecond': 0,
          'infoSort': 1,
          'sourceContent': '',
          'sourceId': '',
          'sourceType': '',
          'answerType': 1,
          'infoContent': '现在听一段较长对话，回答第6~7两小题。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/upload/file/20180625/1529913464213607.mp3',
          'infoContentSourceId': '13629',
          'infoContentSourceType': 1,
          'infoKeyword': '',
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210818009223170',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'How was Leo\'s last weekend?',
              'itemId': '1119210818109886466',
              'itemKeyword': '',
              'itemPaperSort': '2_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 15:57:59',
              'videoSourceContent': '',
              'videoSourceId': '0',
              'answers': [
                {
                  'answerContent': 'Great.',
                  'answerId': '1119210818206355458',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210818109886466',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Not good.',
                  'answerId': '1119210818307018754',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '1119210818109886466',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Just so-so.',
                  'answerId': '1119210818386710530',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '1119210818109886466',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ]
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'On a bus.',
                  'answerId': '1119210818432847874',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210818411876353',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'At a restaurant.',
                  'answerId': '1119210818466402306',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '1119210818411876353',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'In the supermarket.',
                  'answerId': '1119210818546094081',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '1119210818411876353',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210818009223170',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Where did he lose his wallet?',
              'itemId': '1119210818411876353',
              'itemKeyword': '',
              'itemPaperSort': '2_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 15:58:37',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ]
        },
        {
          'answerType': 1,
          'infoContent': '听下面一段较长的对话，回答第8~10三小题。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/upload/file/20180625/1529913551240745.mp3',
          'infoContentSourceId': '13630',
          'infoContentSourceType': 1,
          'infoId': '1119210818629980161',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 2,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'A soccer match.',
                  'answerId': '1119210819389149186',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819380760577',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'A tea party.',
                  'answerId': '1119210819405926401',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '1119210819380760577',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'A school trip.',
                  'answerId': '1119210819435286529',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '1119210819380760577',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210818629980161',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What did Eric have last week?',
              'itemId': '1119210819380760577',
              'itemKeyword': '',
              'itemPaperSort': '2_2_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 15:59:28',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'A farm.',
                  'answerId': '1119210819561115649',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819527561218',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'A fire station.',
                  'answerId': '1119210819586281473',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '1119210819527561218',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'A history museum.',
                  'answerId': '1119210819598864385',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '1119210819527561218',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210818629980161',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Where did they go?',
              'itemId': '1119210819527561218',
              'itemKeyword': '',
              'itemPaperSort': '2_2_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 16:00:24',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Interesting.',
                  'answerId': '1119210819649196033',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819611447298',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Boring.',
                  'answerId': '1119210819657584641',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '1119210819611447298',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Dangerous.',
                  'answerId': '1119210819670167553',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '1119210819611447298',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210818629980161',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What does Eric think of the job as a firefighter?',
              'itemId': '1119210819611447298',
              'itemKeyword': '',
              'itemPaperSort': '2_2_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 16:01:20',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '1119210817879199746',
          'sourceContent': '/upload/file/20171017/1508210896373614.mp3',
          'sourceId': '7073',
          'sourceType': 1
        }
      ]
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '去年夏天，我和家人一起去了一趟昆明。我们在那儿呆了一周，玩得非常开心。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '1119210819779219457',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'qsId': '1119210819695333377',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': '',
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'I went to Kun ming with my family last summer.|I went there last summer.|Last summer.|I went to Kun ming last summer.|We went to Kun ming last summer.|We went there last summer.',
                  'answerId': '1119210819825356802',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819808579585',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210819779219457',
              'isDel': 0,
              'itemAnswerSecond': 15,
              'itemContent': '',
              'itemId': '1119210819808579585',
              'itemKeyword': '',
              'itemPaperSort': '5_1_1',
              'itemPrepareSecond': 10,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180625/1529915147329116.mp3',
              'sourceId': '13632',
              'sourceType': 1,
              'uTime': '2018-06-25 16:25:48',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'We stayed there for a week.|I stayed there for a week.|For a week.|A week.|We stayed there for one week.|I stayed there for one week.|For one week.|One week.',
                  'answerId': '1119210819909242882',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819879882753',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210819779219457',
              'isDel': 0,
              'itemAnswerSecond': 15,
              'itemContent': '',
              'itemId': '1119210819879882753',
              'itemKeyword': '',
              'itemPaperSort': '5_1_2',
              'itemPrepareSecond': 10,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180625/1529915206159982.mp3',
              'sourceId': '13633',
              'sourceType': 1,
              'uTime': '2018-06-25 16:26:47',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ]

        }
      ],
      'isDel': 0,
      'paperId': '1119210815337451522',
      'qsContent': '你将听到两个问题，请根据情景提示的内容用英语进行回答。注意，每个问题问两遍，每个问题你有10秒钟的时间准备，每题的答题时间为15秒钟。\n请看下面的情景提示：',
      'qsId': '1119210819695333377',
      'qsSort': 5,
      'qsTitle': '第五部分 情景问答（计2分）',
      'qsType': 9,
      'sourceContent': '/upload/file/20171018/1508291315935240.mp3',
      'sourceId': '7125',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '{"33480":"10","33481":"10","33482":"10","33483":"10","33484":"10"}',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '1119210819959574529',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'sourceContent': '/upload/file/20190419/1555644203875084.png,/upload/file/20190419/1555644222159912.png,/upload/file/20190419/1555644232161653.png,/upload/file/20190419/1555644238433311.png,/upload/file/20190419/1555644241956801.png',
          'sourceId': '33485',
          'sourceType': 2,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'To protect endangered animals, I think we should do everything we can in our daily life. For example, once we find wild animals are kept by someone, we should call the police. In this way, we can prevent the animals from being hurt. Besides, no trading, no killing. We should not buy or use things made from parts of endangered',
                  'answerId': '1119210820009906178',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210819993128961',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-19 11:10:54',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210819959574529',
              'isDel': 0,
              'itemAnswerSecond': 60,
              'itemContent': '',
              'itemId': '1119210819993128961',
              'itemKeyword': '',
              'itemPaperSort': '1_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '3.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-19 11:25:32',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '1119210819934408706'

        }
      ],
      'isDel': 0,
      'paperId': '1119210815337451522',
      'qsContent': '',
      'qsId': '1119210819934408706',
      'qsSort': 1,
      'qsTitle': '第一部分 看图简述',
      'qsType': 20,
      'sourceContent': '',
      'sourceId': '',
      'sourceType': ''
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '1119210820030877697',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 0,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Mr West walked into the sitting room and turned the radio on. Mrs West was sitting on the sofa at that time. Then, they listened to the six o\'clock news in the sitting room. After the news, Mr West turned the radio off. He went into the next room. When he came back into the sitting room, he had two cups of coffee in his hands. Mr and Mrs West had a drink. After that, they went to the cinema.',
                  'answerId': '1119210820072820738',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820060237826',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820030877697',
              'isDel': 0,
              'itemAnswerSecond': 90,
              'itemContent': 'Mr West walked into the sitting room and turned the radio on. Mrs West was sitting on the sofa at that time. Then, they listened to the six o\'clock news in the sitting room. After the news, Mr West turned the radio off. He went into the next room. When he came back into the sitting room, he had two cups of coffee in his hands. Mr and Mrs West had a drink. After that, they went to the cinema.',
              'itemId': '1119210820060237826',
              'itemKeyword': '',
              'itemPaperSort': '4_1_1',
              'itemPrepareSecond': 60,
              'itemRepetTimes': 1,
              'itemScore': '3.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-06-25 16:23:36',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '1119210820018294785',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '1119210815337451522',
      'qsContent': '你将有1分钟的时间熟悉屏幕上的短文。在听到开始录音的提示后，请将短文朗读一遍，时间为1分半钟。',
      'qsId': '1119210820018294785',
      'qsSort': 4,
      'qsTitle': '第四部分 朗读短文（计3分）',
      'qsType': 5,
      'sourceContent': '/upload/file/20170505/590c41a0d63ad.mp3',
      'sourceId': '3635',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 1,
          'infoContent': '',
          'infoContentImg': '/upload/file/20190416/1555407320912298.png',
          'infoContentImgId': '33172',
          'infoContentSourceContent': '/upload/file/20190416/1555407290202584.mp3',
          'infoContentSourceId': '33171',
          'infoContentSourceType': 1,
          'infoId': '1119210820110569474',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 2,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'thrillers',
                  'answerId': '1119210820177678338',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820152512513',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:35:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820110569474',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'thrillers',
              'itemId': '1119210820152512513',
              'itemKeyword': '',
              'itemPaperSort': '1_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:36:50',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'children\'s',
                  'answerId': '1119210820223815682',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820207038465',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:36:25',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820110569474',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'children\'s\n\n',
              'itemId': '1119210820207038465',
              'itemKeyword': '',
              'itemPaperSort': '1_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:04',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Picture',
                  'answerId': '1119210820303507457',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820261564417',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:37:15',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820110569474',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Picture\n',
              'itemId': '1119210820261564417',
              'itemKeyword': '',
              'itemPaperSort': '1_1_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:15',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'history',
                  'answerId': '1119210820341256193',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820316090370',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:37:23',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820110569474',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'history',
              'itemId': '1119210820316090370',
              'itemKeyword': '',
              'itemPaperSort': '1_1_4',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:23',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'magazines',
                  'answerId': '1119210820387393537',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820358033410',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:37:29',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820110569474',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'magazines',
              'itemId': '1119210820358033410',
              'itemKeyword': '',
              'itemPaperSort': '1_1_5',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:37:29',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '1119210820085403650',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        },
        {
          'answerType': 2,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/upload/file/20190416/1555407290202584.mp3',
          'infoContentSourceId': '33171',
          'infoContentSourceType': 1,
          'infoId': '1119210820731326465',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 2,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Many people like reading. Different people like reading different kinds of books. Here are the results of the discussion "What kind of books do you like reading most?" Bob said he liked to read a bit in bed every night. Thrillers are his favorite, and he made sure he read at least ten pages every night before he went to sleep. Kate is a teacher, and she loves reading books on children\'s behavior. Picture storybooks are Jack\'s favourite, because he doesn\'t have enough time to read many books now. Lucy told us if she has time, she mostly reads history books. Anne likes to read different types of books and magazines.',
                  'answerId': '1119210820936847361',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '1119210820815212545',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2019-04-16 17:34:30',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '1119210820731326465',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Many people like reading. Different people like reading different kinds of books. Here are the results of the discussion "What kind of books do you like reading most?" Bob said he liked to read a bit in bed every night. Thrillers are his favorite, and he made sure he read at least ten pages every night before he went to sleep. Kate is a teacher, and she loves reading books on children\'s behavior. Picture storybooks are Jack\'s favourite, because he doesn\'t have enough time to read many books now. Lucy told us if she has time, she mostly reads history books. Anne likes to read different types of books and magazines.',
              'itemId': '1119210820815212545',
              'itemKeyword': '',
              'itemPaperSort': '1_2_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2019-04-16 17:39:08',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '1119210820085403650',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '1119210815337451522',
      'qsContent': '你将听到一段录音，录音播放两遍。听完录音后，你将有2分钟的时间根据所听内容，键入正确答案，补全信息记录表；之后你将有1分钟的准备时间，根据信息记录表，在2分钟内进行转述，需包含所有要点。现在你有15秒钟的时间阅读题目内容。',
      'qsId': '1119210820085403650',
      'qsSort': 1,
      'qsTitle': '第一部分 信息转述。（计5分）',
      'qsType': 19,
      'sourceContent': '',
      'sourceId': '',
      'sourceType': ''
    },
    {
      'infos': [
        {
          'answerType': 1,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '21014',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Ping-pong.',
                  'answerId': '56554',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32797',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Football.',
                  'answerId': '56555',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32797',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Basketball.',
                  'answerId': '56556',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32797',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21014',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Which sport does Jimmy like best?',
              'itemId': '32797',
              'itemKeyword': '',
              'itemPaperSort': '1_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534231748874852.mp3',
              'sourceId': '13912',
              'sourceType': 1,
              'uTime': '2018-08-14 15:29:09',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Hug each other.',
                  'answerId': '56563',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32800',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Shake hands.',
                  'answerId': '56564',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32800',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Bow.',
                  'answerId': '56565',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32800',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21014',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What will people do when they meet in the boy\'s country?',
              'itemId': '32800',
              'itemKeyword': '',
              'itemPaperSort': '1_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534231792453919.mp3',
              'sourceId': '13913',
              'sourceType': 1,
              'uTime': '2018-08-14 15:29:54',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'The guitar.',
                  'answerId': '56551',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32796',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'The drums.',
                  'answerId': '56552',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32796',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'The violin.',
                  'answerId': '56553',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32796',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21014',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What is Scott interested in now?',
              'itemId': '32796',
              'itemKeyword': '',
              'itemPaperSort': '1_1_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534231897206262.mp3',
              'sourceId': '13914',
              'sourceType': 1,
              'uTime': '2018-08-14 15:31:39',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'At 2:00 pm.',
                  'answerId': '56557',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32798',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'At 2:30 pm.',
                  'answerId': '56558',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32798',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'At 3:00 pm.',
                  'answerId': '56559',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32798',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21014',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'When will the kids volunteer to visit the old people\'s home?',
              'itemId': '32798',
              'itemKeyword': '',
              'itemPaperSort': '1_1_4',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534231944906223.mp3',
              'sourceId': '13915',
              'sourceType': 1,
              'uTime': '2018-08-14 15:32:26',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'By surfing the Internet.',
                  'answerId': '56560',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32799',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By watching TV.',
                  'answerId': '56561',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32799',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By reading in the library.',
                  'answerId': '56562',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32799',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21014',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'How does Eric search for information now?',
              'itemId': '32799',
              'itemKeyword': '',
              'itemPaperSort': '1_1_5',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534232003744556.mp3',
              'sourceId': '13916',
              'sourceType': 1,
              'uTime': '2018-08-14 15:33:46',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12459',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '本部分共有5道小题，每小题你将听到一段对话，每段对话只听一遍。在听每段对话前，你将有5秒钟的时间阅读题目；听完后，你还有5秒钟的时间在屏幕上点击你认为最合适的备选答案。',
      'qsId': '12459',
      'qsSort': 1,
      'qsTitle': '第一部分 听小对话回答问题（计5分）',
      'qsType': 1,
      'sourceContent': '/upload/file/20170919/1505806375542495.mp3',
      'sourceId': '6926',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 1,
          'infoContent': '现在听一段较长对话，回答第6~7两小题。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/upload/file/20180814/1534232109759899.mp3',
          'infoContentSourceId': '13917',
          'infoContentSourceType': 1,
          'infoId': '21016',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Buy a nice gift.',
                  'answerId': '56578',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32805',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Enter high school.',
                  'answerId': '56579',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32805',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Finish high school.',
                  'answerId': '56580',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32805',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21016',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What will the boy\'s brother do next week?',
              'itemId': '32805',
              'itemKeyword': '',
              'itemPaperSort': '2_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:35:27',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': '12 dollars.',
                  'answerId': '56575',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32804',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': '20 dollars.',
                  'answerId': '56576',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32804',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': '22 dollars.',
                  'answerId': '56577',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32804',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21016',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'How much is the boy probably going to spend?',
              'itemId': '32804',
              'itemKeyword': '',
              'itemPaperSort': '2_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:36:39',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12460',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        },
        {
          'answerType': 1,
          'infoContent': '听下面一段较长的对话，回答第8~10三小题。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '/upload/file/20180814/1534232243380382.mp3',
          'infoContentSourceId': '13918',
          'infoContentSourceType': 1,
          'infoId': '21015',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 2,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Classical music.',
                  'answerId': '56572',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32803',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Country music.',
                  'answerId': '56573',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32803',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Pop music.',
                  'answerId': '56574',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32803',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21015',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What kind of music does the girl like best?',
              'itemId': '32803',
              'itemKeyword': '',
              'itemPaperSort': '2_2_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:37:40',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Because he knows Chinese culture very well.',
                  'answerId': '56569',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32802',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Because he used to stay in China for a long time.',
                  'answerId': '56570',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32802',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Because he just enjoys listening to it.',
                  'answerId': '56571',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32802',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21015',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Why does the boy like Chinese pop music?',
              'itemId': '32802',
              'itemKeyword': '',
              'itemPaperSort': '2_2_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:38:27',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'The girl.',
                  'answerId': '56566',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32801',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'The boy\'s grandmother.',
                  'answerId': '56567',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32801',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'The girl\'s grandmother.',
                  'answerId': '56568',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32801',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21015',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Who is a big fan of Peking Opera?',
              'itemId': '32801',
              'itemKeyword': '',
              'itemPaperSort': '2_2_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:39:32',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12460',
          'sourceContent': '/upload/file/20171017/1508210896373614.mp3',
          'sourceId': '7073',
          'sourceType': 1
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '本部分共有5道小题，你将听到两段较长对话，每段对话听两遍。在听每段对话前，你将有时间阅读相关小题，每小题5秒钟；听完后，每小题你还有5秒钟的时间在屏幕上点击你认为最合适的备选答案。',
      'qsId': '12460',
      'qsSort': 2,
      'qsTitle': '第二部分 听较长对话回答问题（计5分）',
      'qsType': 3,
      'sourceContent': '/upload/file/20170505/590c41a0c95be.mp3',
      'sourceId': '3629',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 1,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '21017',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'CZ3109.',
                  'answerId': '56587',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32808',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'CA3019.',
                  'answerId': '56588',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32808',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'CB0319.',
                  'answerId': '56589',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32808',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21017',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Which flight was put off?',
              'itemId': '32808',
              'itemKeyword': '',
              'itemPaperSort': '3_1_1',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:40:48',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Because of the rain.',
                  'answerId': '56584',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32807',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Because of the storm.',
                  'answerId': '56585',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32807',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Because of the snow.',
                  'answerId': '56586',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32807',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21017',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'Why was the flight put off?',
              'itemId': '32807',
              'itemKeyword': '',
              'itemPaperSort': '3_1_2',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:41:20',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'By car.',
                  'answerId': '56581',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32806',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By taxi.',
                  'answerId': '56582',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32806',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By bus.',
                  'answerId': '56583',
                  'answerIsRight': 1,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32806',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21017',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'How can the passengers get to the hotel?',
              'itemId': '32806',
              'itemKeyword': '',
              'itemPaperSort': '3_1_3',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:41:59',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Lunch.',
                  'answerId': '56590',
                  'answerIsRight': 0,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32809',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Supper.',
                  'answerId': '56591',
                  'answerIsRight': 1,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32809',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'Breakfast.',
                  'answerId': '56592',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32809',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21017',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'What meal will the airport provide for free?',
              'itemId': '32809',
              'itemKeyword': '',
              'itemPaperSort': '3_1_4',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:42:44',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'By calling South China Airlines.',
                  'answerId': '56593',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32810',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By asking the clerks in the airport.',
                  'answerId': '56594',
                  'answerIsRight': 0,
                  'answerSort': 2,
                  'isDel': 0,
                  'itemId': '32810',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                },
                {
                  'answerContent': 'By searching on the website of the airport.',
                  'answerId': '56595',
                  'answerIsRight': 0,
                  'answerSort': 3,
                  'isDel': 0,
                  'itemId': '32810',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21017',
              'isDel': 0,
              'itemAnswerSecond': 5,
              'itemContent': 'How can the passengers get more information?',
              'itemId': '32810',
              'itemKeyword': '',
              'itemPaperSort': '3_1_5',
              'itemPrepareSecond': 5,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:44:04',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12461',
          'sourceContent': '/upload/file/20180814/1534232423724051.mp3',
          'sourceId': '13919',
          'sourceType': 1
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '本部分共有5道小题。你将听到一篇短文，短文听两遍。你将有时间阅读相关小题，每小题5秒钟；每小题你还有5秒钟的时间在屏幕上点击你认为最合适的备选答案。',
      'qsId': '12461',
      'qsSort': 3,
      'qsTitle': '第三部分 听短文回答问题（计5分）',
      'qsType': 4,
      'sourceContent': '/upload/file/20171018/1508290685747997.mp3',
      'sourceId': '7121',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '21018',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 0,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'Children today have many things to play with. They can watch TV, play video games or use the Internet. But what do you think children did for fun long time ago? They read books. Some of you may ask, "Are books really fun?" Believe it or not, books can certainly provide things that TV or computer cannot. Since books use only words to tell a story, they can improve your imagination. You can picture the characters and stories in your mind. The words and sentences in the books are also very live but cannot be found on TV or websites. They are sometimes so beautiful and touching. Books also help us to think harder and deeper. As we continue to read, we ask questions to ourselves and try to find out the answers. Remember: the more you read, the more you grow.',
                  'answerId': '56596',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32811',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21018',
              'isDel': 0,
              'itemAnswerSecond': 90,
              'itemContent': 'Children today have many things to play with. They can watch TV, play video games or use the Internet. But what do you think children did for fun long time ago? They read books. Some of you may ask, "Are books really fun?" Believe it or not, books can certainly provide things that TV or computer cannot. Since books use only words to tell a story, they can improve your imagination. You can picture the characters and stories in your mind. The words and sentences in the books are also very live but cannot be found on TV or websites. They are sometimes so beautiful and touching. Books also help us to think harder and deeper. As we continue to read, we ask questions to ourselves and try to find out the answers. Remember: the more you read, the more you grow.',
              'itemId': '32811',
              'itemKeyword': '',
              'itemPaperSort': '4_1_1',
              'itemPrepareSecond': 60,
              'itemRepetTimes': 1,
              'itemScore': '3.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:44:46',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12462',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '你将有1分钟的时间熟悉屏幕上的短文。在听到开始录音的提示后，请将短文朗读一遍，时间为1分半钟。',
      'qsId': '12462',
      'qsSort': 4,
      'qsTitle': '第四部分 朗读短文（计3分）',
      'qsType': 5,
      'sourceContent': '/upload/file/20170505/590c41a0d63ad.mp3',
      'sourceId': '3635',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '我通常在5:30吃晚餐。晚餐结束后我会跟父母一起散步。',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '21019',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 1,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'I have dinner at half past five.|I eat dinner at half past five.|I have dinner at five thirty.|I eat dinner at five thirty.|At five thirty.|At half past five.|I usually have dinner at half past five.|I usually eat dinner at half past five.|I usually have dinner at five thirty.|I usually eat dinner at five thirty.',
                  'answerId': '56598',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32813',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21019',
              'isDel': 0,
              'itemAnswerSecond': 15,
              'itemContent': '',
              'itemId': '32813',
              'itemKeyword': '',
              'itemPaperSort': '5_1_1',
              'itemPrepareSecond': 10,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534232713973060.mp3',
              'sourceId': '13920',
              'sourceType': 1,
              'uTime': '2018-08-14 15:45:14',
              'videoSourceContent': '',
              'videoSourceId': '0'
            },
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'I usually take a walk with my parents after dinner.|I usually go for a walk with my parents after dinner.|I usually have a walk with my parents after dinner.|I usually walk with my parents after dinner.|Take a walk with my parents.|Go for a walk with my parents.|Have a walk with my parents.|Walk with my parents.',
                  'answerId': '56597',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32812',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21019',
              'isDel': 0,
              'itemAnswerSecond': 15,
              'itemContent': '',
              'itemId': '32812',
              'itemKeyword': '',
              'itemPaperSort': '5_1_2',
              'itemPrepareSecond': 10,
              'itemRepetTimes': 1,
              'itemScore': '1.00',
              'qsType': 0,
              'sourceContent': '/upload/file/20180814/1534232732195576.mp3',
              'sourceId': '13921',
              'sourceType': 1,
              'uTime': '2018-08-14 15:45:33',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12463',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '你将听到两个问题，请根据情景提示的内容用英语进行回答。注意，每个问题问两遍，每个问题你有10秒钟的时间准备，每题的答题时间为15秒钟。\n请看下面的情景提示：',
      'qsId': '12463',
      'qsSort': 5,
      'qsTitle': '第五部分 情景问答（计2分）',
      'qsType': 9,
      'sourceContent': '/upload/file/20171018/1508291315935240.mp3',
      'sourceId': '7125',
      'sourceType': 1
    },
    {
      'infos': [
        {
          'answerType': 2,
          'infoContent': '',
          'infoContentImg': '',
          'infoContentImgId': '0',
          'infoContentSourceContent': '',
          'infoContentSourceId': '0',
          'infoContentSourceType': 0,
          'infoId': '21020',
          'infoKeyword': '',
          'infoPrepareSecond': 0,
          'infoRepetTimes': 0,
          'infoSort': 1,
          'isDel': 0,
          'items': [
            {
              'answerSort': 0,
              'answerType': 0,
              'answers': [
                {
                  'answerContent': 'I know Green Town very well. I moved here with my parents at the age of five. We have lived here since then. At first, we lived in the north of the town. A few years later, we moved to the center of the town. Green Town is quite different from it used to be. Now it looks like a large beautiful park.|I know a lot about Green Town. When I was five, I moved here with my parents. Since then we have lived here. At first, we lived in the northern part of the town. A few years later, we moved to the center of the town. Green Town is quite different from it used to be. Now it looks like a big beautiful park.|I know Green Town so well. I moved here with my parents when I was five years old. We have been living here since then. We lived in the north of the town at first. After a few years, we moved to the center of the town. Green Town has changed a lot over the years. It\'s a large beautiful park now.|I know much about Green Town. I moved here with my parents when I was five. Since then we have lived here. We lived in the northern part of the town at first. After a few years, we moved to the center of the town. Green Town has changed a lot over the years. It\'s a big beautiful park now.',
                  'answerId': '56599',
                  'answerIsRight': 1,
                  'answerSort': 1,
                  'isDel': 0,
                  'itemId': '32814',
                  'sourceContent': '',
                  'sourceId': '0',
                  'sourceType': ''
                }
              ],
              'cTime': '2017-05-05 09:10:56',
              'imgSourceContent': '',
              'imgSourceId': '0',
              'infoId': '21020',
              'isDel': 0,
              'itemAnswerSecond': 90,
              'itemContent': '要点：\n1. 我对格林镇很了解。五岁时随父母搬到这里，从那以后就住在这里。\n2. 我们先住在镇北，几年后，我们搬到了镇中心。\n3. 现在的格林镇跟过去大不一样，看起来像一个美丽的大公园。',
              'itemId': '32814',
              'itemKeyword': '',
              'itemPaperSort': '6_1_1',
              'itemPrepareSecond': 120,
              'itemRepetTimes': 1,
              'itemScore': '5.00',
              'qsType': 0,
              'sourceContent': '',
              'sourceId': '0',
              'sourceType': '',
              'uTime': '2018-08-14 15:46:26',
              'videoSourceContent': '',
              'videoSourceId': '0'
            }
          ],
          'qsId': '12464',
          'sourceContent': '',
          'sourceId': '',
          'sourceType': ''
        }
      ],
      'isDel': 0,
      'paperId': '2392',
      'qsContent': '你有2分钟的时间阅读屏幕上的要点提示，并作答题准备。在听到开始录音的提示后，请用英语进行话题表述，你的表述应不少于7句话，时间为1分半钟。',
      'qsId': '12464',
      'qsSort': 6,
      'qsTitle': '第六部分 话题简述（计5分）',
      'qsType': 12,
      'sourceContent': '/upload/file/20170505/590c41a0d9dbf.mp3',
      'sourceId': '3639',
      'sourceType': 1
    }
  ],
  'slack': '0.0',
  'sort': 0,
  'sourceContent': '/upload/file/20180814/1534228906472604.mp3',
  'sourceId': '13911',
  'sourceType': 1,
  'srcFrom': 0,
  'studyLevel': '',
  'uTime': '2018-09-04 16:52:29',
  'userId': ''
};

